<?php


// Firebase API Key
define('FIREBASE_API_KEY', 'AAAAFiy0ehc:APA91bHE4XCrUGt1lUmmnprPUbRf5iQFS9c7QS62qV5yRMxEBKN-WsiRCpSOBr-JuRLuZXyx1H_3KPuIHcTt4XALxPHB-OV4UeRTykyxdBvcKFTyAa0CqIoBxeRMmuxH2fnbi_Ch9vLO');
